### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by Hanoosh** [chrisleekr/nodejs-vuejs-mysql-boilerplate#11]
```
Step 16/27 : RUN create-env.sh
 ---> Running in 2703ac7248fd
/bin/sh: create-env.sh: not found
ERROR: Service 'frontend-nuxt' failed to build: The command '/bin/sh -c create-env.sh' returned a non-zero code: 127

```

**Comment by chrisleekr** [comment]
Can you please explain more? 
I checked out the master and had no issue like you have.

**Comment by Hanoosh** [comment]
i just did `docker-compose up -d` and got that error, not sure whats causing that. i had to remove everything related to frontend-nuxt to make it work. ( losing frontend-nuxt )

i'm using docker on windows 10, not sure if that's important, as the image is running on docker.

**Comment by chrisleekr** [comment]
Can you check whether you have the file in your local system - frontend-nuxt/image-files/usr/local/bin/create-env.sh ?

Try with `docker-compose up -d --build`.

**Comment by Hanoosh** [comment]
the file exists, and using `docker-compose up -d --build` got same error


frontend-nuxt/image-files/usr/local/bin/create-env.sh
```
#!/bin/sh

set -e


cat <<EOT > /srv/.env
BASE_URL=${BASE_URL:=/}
API_URL=${API_URL:=http://localhost/api}
FORMAT_DATETIME=${FORMAT_DATETIME:="YYYY-MM-DD HH:MM:SS"}
EOT

exec "$@"

```

**Comment by chrisleekr** [comment]
As I don't have Windows machine, I cannot test what you have. So all I can give is simply recommendations.

1. Can you clear all cache in your machine and try again?
`docker system prune -a`

2. I have a doubt that it may be the permission issue with Windows docker.
You can update `Dockerfile` for `frontend-nuxt` to see whether it is copying `image-files` properly.
If you find the solution, could you do pull request? :)

**Comment by Hanoosh** [comment]
No problem, i will try to check whats the problem. docker system prune -a did not help

**Comment by chrisleekr** [comment]
Hey @Hanoosh , how's going with this issue? Have you found any solution?
