### ISSUE TITLE
clustering ?

### ISSUE THREAD

**Issue by Hanoosh** [chrisleekr/nodejs-vuejs-mysql-boilerplate#12]
possible to implement clustering on the api ?

**Comment by chrisleekr** [comment]
What do you mean?

**Comment by Hanoosh** [comment]
> Cluster Module — Cores Engagement:
> NodeJs single-threaded nature is by default using a single core of a processor. Therefore NodeJs introduced a cluster module to spawn processes. “Cluster” was introduced to scale an application execution on multiple processor cores by creating worker processes. Worker processes share a single port, therefore, requests are routed through a single port

https://medium.com/tech-tajawal/clustering-in-nodejs-utilizing-multiple-processor-cores-75d78aeb0f4f

 i'm trying to make the API part scale-able so i can start a new node ( physical server ) when needed.

basically my plane is :

1x NGINX LoadBalancer  ( picks from API servers pool ) 
     1- API ( cluster ) using pm2 + nginx ? http://pm2.keymetrics.io/docs/usage/cluster-mode/
     2- API ( cluster )
     3- API....4, 5...etc

**Comment by chrisleekr** [comment]
Oh, I see what you mean.

Yeah, that architecture should be feasible. I haven't tried this project.

**Comment by Hanoosh** [comment]
i will try my luck, maybe you can add it later as a feature branch. also with Graphql.

**Comment by chrisleekr** [comment]
Close the issue.
